# Chocolatey package installation task for Dev Box.
name: choco
description: Installs a Chocolatey package.
author: Platform Team
command: ".\\Choco.ps1 -Package {{package}} -Version {{version}} -IgnoreChecksums {{ignoreChecksums}}"
inputs:
  package:
    type: string
    defaultValue: ""
    required: true
    description: The name of the Chocolatey package to install (for example, "git"). See https://chocolatey.org/packages.
  version:
    type: string
    defaultValue: ""
    required: false
    description: The version of the Chocolatey package to install.
  ignoreChecksums:
    type: string
    defaultValue: "false"
    required: false
    description: Set to "true" to ignore checksums when installing the package.
